version: "3.8"
services:
  sam-client:
    image: ghcr.io/mrsyee/sam-remove-background-client:latest
    container_name: sam-remove-background-client
    build:
      context: .
      dockerfile: Dockerfiles/client.Dockerfile
    ports:
      - 7860:7860
    environment:
      - API_SERVER_URL=http://sam-server:8888
    # stdin_open: true
    # tty: true
    # restart: 'no'
    networks:
      - sam-network

  sam-server:
    image: ghcr.io/mrsyee/sam-remove-background-server:latest
    container_name: sam-remove-background-server
    build:
      context: .
      dockerfile: Dockerfiles/server.Dockerfile
    volumes:
      - ./checkpoint:/app/checkpoint
    ports:
      - 8888:8888
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]
    networks:
      - sam-network

  triton:
    image: nvcr.io/nvidia/tritonserver:23.04-py3
    container_name: sam_triton
    command: tritonserver --model-repository=/models
    volumes:
      - ./model_repository:/models
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    networks:
      - sam-network

networks:
  sam-network:
