version: "3.8"
services:
  sam-client:
    image: ghcr.io/mrsyee/sam-remove-background-client:latest
    container_name: sam-remove-background-client
    ports:
      - 7860:7860
    # stdin_open: true
    # tty: true
    # restart: 'no'
    networks:
      - sam-network

  sam-server:
    image: ghcr.io/mrsyee/sam-remove-background-server:latest
    container_name: sam-remove-background-server
    volumes:
      - ./checkpoint:/app/checkpoint
    ports:
      - 8888:8888
    networks:
      - sam-network

networks:
  sam-network:
