kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      additionalScrapeConfigs:
        - job_name: gpu-metrics
          scrape_interval: 1s
          metrics_path: /metrics
          scheme: http
          kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - gpu-operator
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: kubernetes_node
  grafana:
    additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      basicAuth: false
      isDefault: false
      editable: false
    adminPassword: admin
    ingress:
      enabled: false
      ingressClassName: ""
      annotations: {}
      labels: {}
    service:
      enabled: true
      type: LoadBalancer
      port: 3000
      targetPort: 3000
      annotations: {}
      labels: {}
      portName: http